name: Generate Snake Animation

on:
  schedule:
    # Chạy tự động vào lúc nửa đêm mỗi ngày
    - cron: "0 0 * * *"
  
  # Cho phép bạn bấm nút chạy thủ công từ tab Actions
  workflow_dispatch:
  
  # Chạy mỗi khi có push lên nhánh main
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
